openapi: 3.0.0

info:
  description: >
    Land Cover Classification System Web Service. You can find out more about LCCS-WS at [https://github.com/brazil-data-cube/lccs-ws](https://github.com/brazil-data-cube/lccs-ws)

  version: '0.2.0'

  title: Land Cover Classification System Web Service

  contact:
    name: Fabiana Zioti
    email: fabi.zioti@gmail.com

  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

servers:
  - url: 'https://localhost/lccs-ws'
    description: Production server


paths:

  '/classification_systems':
    get:
      tags:
        - Classification Systems
      summary: List of Classification System.
      description: Retrieve list of available classification systems.
      operationId: getClassificationSystems
      responses:
        '200':
          $ref: '#/components/responses/ClassificationSystems'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      tags:
       - Classification Systems
      summary: >
        The server returns 201 in the response. The request was
        successful and a new classification system was created.
      operationId: postClassSystem
      requestBody:
        description: "Informations to create a new classification system"
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/class_system_body'
      responses:
        '201':
          description: "Information of new classification system"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/class_system_body'

  '/classification_systems/{system_id}':
    parameters:
       - $ref: '#/components/parameters/system_id'
    get:
      tags:
        - Classification Systems
      summary: >
        Describe the classification system with id `system_id`
      description: Returns information of classification system by Id.
      operationId: describeClassificationSystem
      responses:
        '200':
          $ref: '#/components/responses/ClassificationSystem'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  '/classification_systems/{system_id}/classes':
    get:
      tags:
        - Classes
      summary: fetch classes
      description: >
        Fetch classes of the classification with id `system_id`.
      operationId: getClasses
      parameters:
        - $ref: '#/components/parameters/system_id'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Classes'

    post:
      tags:
      - Classes
      summary: >
        The server returns 201 in the response. The request was
        successful and a new class was created.
      operationId: postClasses
      parameters:
        - $ref: '#/components/parameters/system_id'
      requestBody:
        description: "Informations to create a new class."
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/class_body'
      responses:
        '201':
          description: "Information of new class"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/class_body'

  '/classification_systems/{system_id}/styles':
    get:
      tags:
        - Styles
      summary: fetch styles
      description: >
        Fetch styles of the classification with id `system_id`.
      operationId: getStyles
      parameters:
        - $ref: '#/components/parameters/system_id'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Styles'

  '/classification_systems/{system_id}/classes/{class_id}':
    get:
      tags:
        - Classes
      summary: fetch a single class.
      description: >
          Fetch the classe with id `class_id` in the classification
          system  with id `system_id`.
      operationId: getClasse
      parameters:
          - $ref: '#/components/parameters/system_id'
          - $ref: '#/components/parameters/class_id'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Classe'

  '/mappings/{system_id_source}':
    get:
      tags:
        - Mappings
      summary: Retrives avaliable classification systems mappings.
      operationId: getAvailablesMappings
      parameters:
        - $ref: '#/components/parameters/system_id_source'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Availables_Mappings'

  '/mappings/{system_id_source}/{system_id_target}':
    get:
      tags:
        - Mappings
      summary: Retrives classification systems mappings.
      description: Mapping of classification systems.
      operationId: getMappings
      parameters:
        - $ref: '#/components/parameters/system_id_source'
        - $ref: '#/components/parameters/system_id_target'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Mappings'

components:

  #-------------------------------
  # Reusable operation parameters
  #-------------------------------

  parameters:

    system_id:
      name: system_id
      in: path
      description: Identifier (name) of a classification system
      required: true
      schema:
        type: string

    class_id:
      name: class_id
      in: path
      description: Identifier (name) of a class
      required: true
      schema:
        type: string

    system_id_source:
      name: system_id_source
      in: path
      description: Identifier (name) of a source classification system
      required: true
      schema:
        type: string

    system_id_target:
      name: system_id_target
      in: path
      description: Identifier (name) of a target classification system
      required: true
      schema:
        type: string


  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------

  schemas:

    class_system_body:
      type: object
      required:
        - authority_name
        - name
        - description
        - version
      properties:
        name:
          type: string
        authority_name:
          type: string
        description:
          type: string
        version:
          type: string

    class_body:
      type: object
      required:
        - name
        - code
        - description
      properties:
        name:
          type: string
        code:
          type: string
        description:
          type: string
        parent_name:
          type: string

    classification_system:
      type: object
      required:
        - id
        - name
        - links
      properties:
        id:
          type: number
        name:
          type: string
        authority_name:
          type: string
        description:
          type: string
        version:
          type: string
        styles:
          type: array
          items:
            $ref: "#/components/schemas/link"
          example:
            - href: http://localhost/lccs_ws/system_id/styles/style_format
              rel: item
              title: Styles
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"
          example:
            - href: http://data.example.com/buildings
              rel: item

    classification_systems:
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    classes:
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    classe:
      type: object
      required:
        - name
        - id
        - links
      properties:
        id:
          type: number
        name:
          type: string
        code:
          type: string
        description:
          type: string
        parent:
          type: object
          items:
            $ref: "#/components/schemas/classe"
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    mapping:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"
        description:
          type: string
        degree_of_similarity:
          type: number

    mappings:
      type: array
      items:
        $ref: "#/components/schemas/mapping"

    availables_mappings:
      type: array
      items:
        $ref: "#/components/schemas/classification_systems"

    styles:
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    link:
      description: A generic link.
      type: object
      required:
        - href
        - rel
      properties:
        href:
          type: string
          format: url
          example: 'http://localhost/lccs_ws/classification_system'
        rel:
          type: string
          example: child
        title:
          type: string
          example: Child

    exception:
      type: object
      description: >
        Information about the exception: an error code plus an optional description.
      required:
        - code
      properties:
        code:
          type: string
        description:
          type: string

  responses:


    ClassificationSystems:
      description: >
        The classsification systems shared by this API.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classification_systems'

    ClassificationSystem:
      description: >
        Information about classification system id `system_id`.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classification_system'

    Classes:
      description: >
        The response is a document consisting of classes in the classification system.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classes'

    Classe:
      description: >
        fetch the classe with id `class_id` in the classification system
        with id `system_id`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classe'

    Mappings:
      description: >
        fetch the mapping with `system_id_source` and `system_id_target`.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/mappings'

    Availables_Mappings:
      description: >
        fetch all mappings availables with `system_id_source`.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/availables_mappings'

    Styles:
      description: >
        The response is a document consisting of all styles in the classification system.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/styles'

    ServerError:
      description: >
        A server error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception'
        text/html:
          schema:
            type: string

    NotFound:
      description: >
        The requested URI was not found.

    InvalidParameter:
      description: >
        A query parameter has an invalid value.